### ISSUE TITLE
Fine-tune my custom data

### ISSUE THREAD

**Issue by whoafridi** [vgaraujov/Question-Answering-Tutorial#1]
Great after all.

I've specific questions. There is a model sagorsarker/bangla-bert-base already available for Bengali language, also a squad like dataset from google tydiqa contains questions of Bengali. So, `run_squad.py` is just simply work for me ? as simple as that or i Use run_squad_trainer.py ?(updated script) from huggingface repo.

Thank you.

**Comment by vgaraujov** [comment]
Hey @whoafridi,

Yes, it should work correctly. You need to correctly set `model_name_or_path`, `train_file`, and `predict_file` parameter to go ahead. Note that you need to have the same format as the SQuAD dataset to avoid conflicts with `run_squad.py`.

**Comment by whoafridi** [comment]
got it .The dataset is same as Squad format & I correctly work with the parameter.  
Thanks @vgaraujov

**Comment by vgaraujov** [comment]
If you want yo use my notebook, please replace the installation line with this one `!pip install transformers==3.5.1"`

**Comment by whoafridi** [comment]
okay . got it. If I'm go with updated one then changes all the things that required
