### ISSUE TITLE
Error when try this

### ISSUE THREAD

**Issue by whoafridi** [vgaraujov/Question-Answering-Tutorial#2]
Gives an error when running this format with transformers 3.5.1- 
as huggingface -transformers update their script i found it in their legacy folder then download in colab & run 
```py
!export SQUAD_DIR=/content/dataset \
&& python /content/run_squad.py \
  --model_type bert \
  --model_name_or_path sagorsarker/bangla-bert-base \
  --do_train \
  --do_eval \
  --do_lower_case \
  --train_file $SQUAD_DIR/bengali.json \
  --predict_file $SQUAD_DIR/val_data.json \
  --per_gpu_train_batch_size 6 \
  --learning_rate 3e-5 \
  --num_train_epochs 5.0 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir /content/model_output \
  --save_steps 5000 \
  --threads 4 \
```
*error 
```py
Evaluating:   0% 0/16 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/run_squad.py", line 830, in <module>
    main()
  File "/content/run_squad.py", line 819, in main
    result = evaluate(args, model, tokenizer, prefix=global_step)
  File "/content/run_squad.py", line 324, in evaluate
    output = [to_list(output[i]) for output in outputs.to_tuple()]
AttributeError: 'tuple' object has no attribute 'to_tuple'
```

**Comment by vgaraujov** [comment]
Hello @whoafridi 

I have used transformers 2.3.0. I will add the specific confirmation number in the [notebook](https://github.com/vgaraujov/Question-Answering-Tutorial/blob/master/Question_Answering_BERT_Spanish.ipynb) please use it to replicate the results.

**Comment by whoafridi** [comment]
okay . got it. but why not we try the latest one 4.0 . I'm also facing problem with 4.0 & create issue for that in another repo. Pretty boring. Huggingface update their repo quiet while .

**Comment by vgaraujov** [comment]
I would like @whoafridi, however now I am busy with other things. I will work on it early next year.

**Comment by whoafridi** [comment]
Now again said "used bert,albert,distil instead of /content/model_output" 😕 pain
